---
- name: Configure Libreddit container
  community.docker.docker_container:
    name: "{{ container_name }}"
    image: 'libreddit/libreddit:latest-arm'
    pull: true
    env:
      LIBREDDIT_DEFAULT_THEME: "{{ libreddit_theme }}"
      LIBREDDIT_DEFAULT_USE_HLS: "{{ libreddit_hls }}"
      LIBREDDIT_DEFAULT_HIDE_HLS_NOTIFICATION: "{{ libreddit_hls_hide }}"
    ports:
      - "127.0.0.1:{{ ext_port }}:8080"
    restart_policy: unless-stopped
