---
- name: "Run all roles"
  hosts: testvm
  become: true
  vars_files:
    - vars/all_vars.yml

  roles:
    - role: system
      tags: system

    - role: docker
      tags: docker

    - role: homer
      tags:
        - homer
        - containers
      when: enable_homer | default(False)
