---
- name: "Run all roles"
  hosts: raspberry_pi
  become: true
  vars_files:
    - group_vars/main.yml

  roles:
    - role: system
      tags: system

    - role: docker
      tags: docker

    - role: homer
      tags:
        - homer
        - containers
      when: enable_homer | default(False)

    - role: containers/system/pihole
      tags:
        - pihole
        - system
        - containers
      when: enable_pihole | default(False)

    - role: containers/media/libreddit
      tags:
        - libreddit
        - media
        - containers
      when: enable_libreddit | default(False)

    - role: containers/media/openbooks
      tags:
        - openbooks
        - media
        - containers
      when: enable_openbooks | default(False)

    - role: containers/media/jellyfin
      tags:
        - jellyfin
        - media
        - containers
      when: enable_jellyfin | default(False)

    - role: containers/services/nextcloud
      tags:
        - nextcloud
        - services
        - containers
      when: enable_nextcloud | default(False)

    - role: containers/services/vaultwarden
      tags:
        - vaultwarden
        - services
        - containers
      when: enable_vaultwarden | default(False)

    - role: containers/system/portainer
      tags:
        - portainer
        - system
        - containers
      when: enable_portainer | default(False)

    - role: containers/system/watchtower
      tags:
        - watchtower
        - system
        - containers
      when: enable_watchtower | default(False)

    - role: containers/system/nginx
      tags:
        - nginx
      when: enable_nginx | default(False)
