---
- name: Update and upgrade apt packages
  ansible.builtin.apt:
    upgrade: yes
    autoremove: yes
    update_cache: yes

- name: Install unattended upgrades package
  ansible.builtin.package:
    name: unattended-upgrades
    state: present

- name: Install extra packages
  ansible.builtin.apt:
    name: "{{ extra_packages }}"
    state: present

- name: Ensure /etc/sudoers.d/ folder exists
  ansible.builtin.file:
    path: /etc/sudoers.d/
    state: directory
    mode: '0755'

- name: Allow user to sudo without password
  ansible.builtin.lineinfile:
    dest: /etc/sudoers.d/{{ ansible_user }}
    create: true
    mode: '0440'
    regexp: '^{{ ansible_user }}'
    line: '{{ ansible_user }} ALL=(ALL) NOPASSWD:ALL'
    validate: visudo -cf %s

- name: Disable DNS on port 53
  ansible.builtin.lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: '^DNSStubListener'
    line: 'DNSStubListener=no'

- name: Restart Systemd
  ansible.builtin.service:
    name: systemd-resolved
    state: stopped
    enabled: false

- name: Remove symlink on /etc/resolv.conf
  ansible.builtin.file:
    path: /etc/resolv.conf
    state: absent

- name: Create /etc/resolv.conf
  ansible.builtin.file:
    path: /etc/resolv.conf
    state: touch

- name: Add Google DNS for installation
  ansible.builtin.lineinfile:
    path: /etc/resolv.conf
    line: 'nameserver 8.8.8.8'