---
#
# From: https://lindevs.com/install-lazydocker-on-ubuntu/
#

- name: Check if Lazydocker is installed
  command: which lazydocker
  changed_when: false
  failed_when: lazydocker_installed.rc not in [0,1]
  register: lazydocker_installed

- name: Get Linux Architecture
  ansible.builtin.shell: | 
    ARCH=$(uname -m)
    case $ARCH in
        i386|i686) ARCH=x86 ;;
        armv6*) ARCH=armv6 ;;
        armv7*) ARCH=armv7 ;;
        aarch64*) ARCH=arm64 ;;
    esac
    echo $ARCH
  register: linux_architecture
  when: lazydocker_installed.rc not in [ 0 ]

- name: Install Lazydocker
  ansible.builtin.shell: |
    ARCH={{ linux_architecture.stdout }}
  
    GITHUB_LATEST_VERSION=$(curl -s "https://api.github.com/repos/jesseduffield/lazydocker/releases/latest" | grep -Po '"tag_name": "v\K[0-9.]+')
    GITHUB_FILE="lazydocker_${GITHUB_LATEST_VERSION}_$(uname -s)_${ARCH}.tar.gz"
    curl -Lo lazydocker.tar.gz "https://github.com/jesseduffield/lazydocker/releases/latest/download/${GITHUB_FILE}"
  when: lazydocker_installed.rc not in [ 0 ]

- name: Create tmp directory
  ansible.builtin.file:
    path: "{{ home_dir }}/lazydocker-temp"
    state: directory
  when: lazydocker_installed.rc not in [ 0 ]

- name: Unzip tar.gz file
  ansible.builtin.command: "tar -xvf {{ home_dir }}/lazydocker.tar.gz -C {{ home_dir }}/lazydocker-temp"
  when: lazydocker_installed.rc not in [ 0 ]

- name: Move binary file to '/usr/local/bin' directory
  command: sudo mv "{{ home_dir }}/lazydocker-temp/lazydocker" /usr/local/bin
  when: lazydocker_installed.rc not in [ 0 ]

- name: Verifies that lazydocker is installed
  ansible.builtin.command: lazydocker --version
  register: lazydocker_version
  changed_when: false
  failed_when: false
  when: lazydocker_installed.rc not in [ 0 ]

- name: Remove lazydocker tmp directory and tar.gz file
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ home_dir }}/lazydocker.tar.gz"
    - "{{ home_dir }}/lazydocker-temp"
  when: lazydocker_installed.rc not in [ 0 ]