---
- name: Configure OpenBook container
  community.docker.docker_container:
    name: "{{ container_name }}"
    image: 'evanbuss/openbooks:latest'
    pull: true
    command: --persist --searchbot searchook --name {{ openbook_irc_username }} --useragent "HexChat 2.16.1" --log true
    ports:
      - "{{ ext_port }}:80"
    volumes:
      - "{{ docker_dir }}/openbooks:/books"
    restart_policy: unless-stopped
