---
- name: Configure Nginx Proxy Manager container
  community.docker.docker_container:
    name: nginxproxymanager
    hostname: nginxproxymanager
    image: 'jc21/nginx-proxy-manager:latest'
    pull: true
    volumes:
      - '{{ docker_dir }}/nginx:/data'
      - '{{ docker_dir }}/letsencrypt:/etc/letsencrypt'
    networks:
      - name: host
    restart_policy: unless-stopped
