---
- name: Create the icons folder
  ansible.builtin.file:
    path: "{{ docker_dir }}/{{ container_name }}/tools/homer-icons"
    state: directory
    mode: 0755
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Copy the icons
  ansible.builtin.copy:
    src: "files/icons/{{ item.path.split('/')[-1] }}.png"
    dest: "{{ docker_dir }}/{{ container_name }}/tools/homer-icons"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644
  when: lookup('vars', 'enable_' + item.path.split('/')[-1]) | default(False) and lookup('vars', item.path.split('/')[-1])['dashboard_url'] is defined
  with_items: "{{ containers.files }}"

- name: Copy other icons
  ansible.builtin.copy:
    src: "files/icons/{{ item }}.png"
    dest: "{{ docker_dir }}/{{ container_name }}/tools/homer-icons"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644
  with_items:
    - "fritzbox"
    - "pihole"

- name: Copy the logo
  ansible.builtin.copy:
    src: "files/icons/logo.png"
    dest: "{{ docker_dir }}/{{ container_name }}/tools/homer-icons"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644

- name: Copy the custom stylesheet
  ansible.builtin.copy:
    src: "files/custom.css"
    dest: "{{ docker_dir }}/{{ container_name }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644

- name: Generate the Homer config file
  ansible.builtin.template:
    src: config.yml.j2
    dest: "{{ docker_dir }}/{{ container_name }}/config.yml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644
