---
- name: Deploy Portainer container
  community.docker.docker_container:
    name: "{{ container_name }}"
    image: 'portainer/portainer-ce:latest'
    pull: true
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '{{ docker_dir }}/portainer:/data'
    ports:
      - '8000:8000'
      - '{{ ext_port }}:9000'
      - '9443:9443'
    restart_policy: unless-stopped