---
- name: Deploy Portainer container
  community.docker.docker_container:
    name: "{{ container_name }}"
    image: 'portainer/portainer-ce:latest'
    pull: true
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '{{ docker_dir }}/portainer:/data'
    labels: 
      com.centurylinklabs.watchtower.monitor-only: 'true'
    ports:
      - '127.0.0.1:8000:8000'
      - '127.0.0.1:{{ ext_port }}:9000'
      - '127.0.0.1:9443:9443'
    restart_policy: unless-stopped