---
- name: Make sure the Watchtower container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "containrrr/watchtower"
    pull: yes
    state: 'started'
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    env:
      WATCHTOWER_NOTIFICATION_URL: "{{ watchtower_notification_url }}"
      WATCHTOWER_CLEANUP: "true"
      TZ: "{{ timezone }}"
    restart_policy: unless-stopped