---
- name: Deploy VaultWarden
  community.docker.docker_container:
    name: "{{ container_name }}"
    image: vaultwarden/server:latest
    ports:
      - "127.0.0.1:{{ ext_port }}:80"
    volumes: 
      - "{{ docker_dir }}/vaultwarden:/data/"
    restart_policy: unless-stopped