---
- name: Deploy MariaDB server
  community.docker.docker_container:
    name: mariadb
    image: mariadb:latest
    volumes:
      - "{{ docker_dir }}/mariadb:/var/lib/mysql"
    env:
      MYSQL_ROOT_PASSWORD: "{{ MYSQL_ROOT_PASSWORD }}"
      MYSQL_PASSWORD: "{{ MYSQL_PASSWORD }}"
      MYSQL_DATABASE: "{{ MYSQL_DATABASE }}"
      MYSQL_USER: "{{ MYSQL_USER }}"
    restart_policy: unless-stopped

- name: Deploy Nextcloud
  community.docker.docker_container:
    name: "{{ container_name }}"
    image: nextcloud:latest
    ports:
      - "127.0.0.1:{{ ext_port }}:80"
    links:
      - "mariadb:/var/lib/mysql"
    volumes:
      - "{{ docker_dir }}/nextcloud:/var/www/html"
    env:
      MYSQL_PASSWORD: "{{ MYSQL_PASSWORD }}"
      MYSQL_DATABASE: "{{ MYSQL_DATABASE }}"
      MYSQL_USER: "{{ MYSQL_USER }}"
      MYSQL_HOST: "{{ MYSQL_HOST }}"
    restart_policy: unless-stopped
