---
- name: Configure Jellyfin container
  community.docker.docker_container:
    name: "{{ container_name }}"
    image: 'jellyfin/jellyfin:latest'
    pull: true
    ports:
      - "127.0.0.1:{{ ext_port }}:8096"
    volumes:
      - "{{ docker_dir }}/jellyfin/config:/config"
    restart_policy: unless-stopped

- name: Add {{ container_name }} to the NGINX network (reverse-proxy)
  docker_network:
    name: ngx_internal_network
    connected:
      - "{{ container_name }}"
    appends: yes
  when: enable_nginx
