---
- name: Configure Jellyfin container
  community.docker.docker_container:
    name: "{{ container_name }}"
    image: 'jellyfin/jellyfin:latest'
    pull: true
    ports:
      - "{{ ext_port }}:8096"
    volumes:
      - "{{ docker_dir }}/jellyfin/config:/config"
    restart_policy: unless-stopped
